re-write in go

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,9 +1,9 @@
-version: 2
+version: 2.1
 
 defaults: &defaults
-  working_directory: ~/app
+  working_directory: /tmp/app
   docker:
-    - image: cimg/node:17.9.1
+    - image: cimg/go:1.22.3
 
 jobs:
   setup:
@@ -12,60 +12,76 @@ jobs:
       - checkout
       - restore_cache:
           keys:
-            - v1-{{ .Branch }}
-            - v1-
+            - go-mod-v1-{{ .Branch }}
+            - go-mod-v1
       - run:
-          name: Install dependencies
-          command: yarn install
+          name: Download dependencies
+          command: go mod vendor
       - save_cache:
-          key: v1-{{ .Branch }}
+          key: go-mod-v1-{{ .Branch }}-{{ epoch }}
           paths:
-            - node_modules
+            - vendor
       - persist_to_workspace:
           root: .
           paths:
             - .
 
-  # lint:
-  #   <<: *defaults
-  #   steps:
-  #     - attach_workspace:
-  #         at: .
-  #     - run:
-  #         name: Run linters
-  #         command: |
-  #           yarn lint
+  lint:
+    <<: *defaults
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Lint
+          command: |
+            bad_files=$(gofmt -l . | (grep -v ^vendor/ || :))
+            if [[ "${bad_files}" != "" ]]; then
+              echo "Lint failed on the following files:"
+              echo ${bad_files}
+              exit 1
+            fi
 
-  build-publish:
+  build:
+    <<: *defaults
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Build
+          command: |
+            go build -mod vendor -o ./build/ ./cmd/*
+
+  publish:
     <<: *defaults
     steps:
       - attach_workspace:
           at: .
       - setup_remote_docker:
           docker_layer_caching: true
-          version: 20.10.12
       - run:
-          name: Build Docker image
+          name: Build container image
           command: |
-            docker build . -t ghcr.io/markormesher/darwin-to-mqtt:$(git describe)
+            docker build /tmp/app -f Containerfile -t ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)
             docker image ls
       - run:
-          name: Maybe publish Docker image
+          name: Maybe publish container image
           command: |
-            # publish tagged commits only
             if ! git describe --exact-match HEAD > /dev/null 2>&1; then echo "Not on tagged commit - nothing to do"; exit 0; fi
             echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
-            docker push ghcr.io/markormesher/darwin-to-mqtt:$(git describe)
+            docker push ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)
 
 workflows:
   version: 2
   main:
     jobs:
       - setup
-      # - lint:
-      #     requires:
-      #       - setup
-      - build-publish:
+      - lint:
           requires:
             - setup
-            # - lint
+      - build:
+          requires:
+            - setup
+      - publish:
+          requires:
+            - lint
+            - build
